# Generated by Django 3.1.6 on 2021-02-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('SN', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=255)),
                ('Profession', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
